### ISSUE TITLE
What actually shows triggers a line item in the changelog?

### ISSUE THREAD

**Issue by rjygraham** [TriPSs/conventional-changelog-action#100]
I've tried several different ways to generate a changelog but have come up with an empty changelog each time. What is this actually reading from in order to compile the list of changes?

**Comment by TriPSs** [comment]
Hi, [conventional commits](https://www.conventionalcommits.org/en/v1.0.0) are used to generate the changelog.

**Comment by rjygraham** [comment]
Thank you. I'm a noob re: conventional commits and was thinking conventional vs unconventional. Weeee! =)
