### ISSUE TITLE
refactor type skipped

### ISSUE THREAD

**Issue by Claiyc** [TriPSs/conventional-changelog-action#103]
Hey

it seems like the "refactor"-type is not supported (will be skipped) as commit message.

example:
```
refactor(test): something important

this refactors something important
```
-> will be ignored

```
feat(test): something important

this refactors something important
```
-> works fine

preset is angular

Is this intended? How can I enable the refactor -type?

**Comment by TriPSs** [comment]
Hi, this depends on the preset and is not necessarily related to this action. If the preset does not add it to the changelog then we see it as a empty changelog.

**Comment by TriPSs** [comment]
From the angular preset README:
```
Type
If the prefix is feat, fix or perf, it will appear in the changelog. However if there is any BREAKING CHANGE, the commit will always appear in the changelog.
```

**Comment by Claiyc** [comment]
thx for the quick answer!
I don't quiet understand yet (sry I am relatively new to github actions). Where is the angular preset defined? What other presets are supported? Can I create my own?

**Comment by TriPSs** [comment]
Np, so [this](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog) is the "tool" that is being used, in that README is described what presets are available:
```
preset
Type: string Possible values: 'angular', 'atom', 'codemirror', 'ember', 'eslint', 'express', 'jquery', 'jscs', 'jshint'

It's recommended to use a preset so you don't have to define everything yourself. Presets are names of built-in config.

A scoped preset package such as @scope/conventional-changelog-custom-preset can be used by passing @scope/custom-preset to this option.
```

What you can then do is checkout those presets and see which one fits you the best.

For example here is the [angular preset](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular), in the same repo are also the other presets.
