### ISSUE TITLE
github-token clarification…

### ISSUE THREAD

**Issue by ygworldr** [TriPSs/conventional-changelog-action#109]
I have a protected main branch with admins allowed to push and a private token from an admin account set as `github-token: ${{ secrets.ADMIN_RELEASE_TOKEN }}`. However, when running the action, I get:

```
remote: error: GH006: Protected branch update failed for refs/heads/main.       
remote: error: At least 1 approving review is required by reviewers with write access.
```

The token I use has `delete:packages, repo, write:packages` permissions. Should it have more or did I find a bug?

**Comment by TriPSs** [comment]
Hi @ygworldr, sadly I'm not quite sure yet on how to fix this. There is [this](https://medium.com/swlh/bump-bump-bump-d0dab616e83) medium article that describes it on how to achieve this.

**Comment by ygworldr** [comment]
I do not use an automatic build on commit to main, instead, I use the manual way to kick an action. This means I can remove protection, launch the action, and re-create protection as soon as the release is done. A little clunky but not too bad.

**Comment by xsc27** [comment]
Would deploy keys, issue #115, resolve this? I think it could be a cleaner workaround.

**Comment by xsc27** [comment]
In the protected branch settings, you may need to uncheck `Include administrators` and/or add the user to `Restrict who can push to matching branches` if they are not already and "admin" or "maintainer".
![image](https://user-images.githubusercontent.com/1302313/134953312-49325c41-3ba6-4bbc-aae6-42f1244ca5e5.png)

**Comment by xsc27** [comment]
TIL: Deploy keys and GitHub Apps will not get around protected branches that require a PR, i.e.: 
![image](https://user-images.githubusercontent.com/1302313/135047537-5af88e08-aa29-4eb9-b323-a99a45bc3bc0.png)

**Comment by vtertre** [comment]
> Hi @ygworldr, sadly I'm not quite sure yet on how to fix this. There is [this](https://medium.com/swlh/bump-bump-bump-d0dab616e83) medium article that describes it on how to achieve this.

If it can save anyone some time, at this date you still have to use your PAT on the checkout step also, and not only on the `TriPSs/conventional-changelog-action` to push to protected branches.
