### ISSUE TITLE
Giving Error while running the action,since iam new to github i dont know what the problem is 

### ISSUE THREAD

**Issue by adityaSharma369** [TriPSs/conventional-changelog-action#11]
![triPSs](https://user-images.githubusercontent.com/53860201/77824737-e69f8300-712a-11ea-9dce-e4bcbeb55c38.png)

**Comment by natioskar** [comment]
@adityaSharma369 use the tag version - 
```
uses: TriPSs/conventional-changelog-action@v1.3.0
```

It contains the node_modules folder

**Comment by adityaSharma369** [comment]
thanks @natioskar it worked

**Comment by adityaSharma369** [comment]
@natioskar i want some suggestion, i Want same versioning change for go lang applications since it doesnt have package.json,we need to create our own variable called Version so that when ever we push into github with commit the version should bump.so is there any plugins in marketplace in your mind

**Comment by adityaSharma369** [comment]
> @natioskar i want some suggestion, i Want same versioning change for go lang applications since it doesnt have package.json,we need to create our own variable called Version so that when ever we push into github with commit the version should bump.so is there any plugins in marketplace in your mind

Hey i got it @natioskar i have just added package.json file in my go folder then it worked ,thank you
