### ISSUE TITLE
Generate a changelog for a specific lerna package

### ISSUE THREAD

**Issue by onuryartasi** [TriPSs/conventional-changelog-action#114]
Do you have an idea to add  `--lerna-package` feature in mind? 
Like `conventional-changelog -p angular -i CHANGELOG.md -l @scope/package-name`

**Comment by TriPSs** [comment]
The `-l` flag is something they already support? We could think of a way to then add the correct `-l` to the command.

**Comment by onuryartasi** [comment]
Actually, I need commit-path parameter for monorepo project. Your repo doesn't forkable therefore I developed this feature in my repository. I can merge this feature into your repository if you enable the fork feature.

**Comment by TriPSs** [comment]
Not sure what you mean with fork feature? You can fork the repo, it is not disabled.

**Comment by onuryartasi** [comment]
Oh sorry, Browser extension problems, I can see now.
