### ISSUE TITLE
Support creating commits via SSH

### ISSUE THREAD

**Issue by xsc27** [TriPSs/conventional-changelog-action#115]
This would enable the option to use deploy keys.

**Comment by TriPSs** [comment]
Interesting, could you create a PR for this?

**Comment by xsc27** [comment]
I would love to. JS is not my dominant language, so I am not sure when I will be able to get to it.

**Comment by xsc27** [comment]
To make this happen, the `github-token` needs to be optional and the repo to be written to needs to be checked out w/ the correct ssh-key, i.e. a deploy key w/ write access.
