### ISSUE TITLE
Changing prefix seem to scramble version number

### ISSUE THREAD

**Issue by SHuang-Broad** [TriPSs/conventional-changelog-action#117]
Hi,

I'm testing out using this action for automated version bumping for our (work) repo, using my [personal test repo](https://github.com/SHuang-Broad/test-autobump).

I discovered that when changing the `prefix` [here](https://github.com/SHuang-Broad/test-autobump/blob/ebac25ac128433e0748ef344aa83355f40b7da97/.github/workflows/main.yml#L39), the version number seem to be reset or scrambled, as you can see [here](https://github.com/SHuang-Broad/test-autobump/releases).

The sequence of events are: 
* initially I started with no prefix, and `1.0.0` in VERSION.json. It works as intended (1.0.0-1.0.13) until
* I changed the prefix to `vv` for testing, then the version number "rolled" back to `vv1.0.3`, which is 10 back from 1.0.13, seeing that, I experimented more by 
* changing the prefix from `vv` to `lrp_`, now the version becomes `lrp_0.1.0`, and the release page places that before the `vv*` releases

In addition, the `VERSION.json` file seem to have stopped being updated after I changed to `skip-commit: 'true'`. Is this intended, and/or related?

Thanks!
Steve

**Comment by TriPSs** [comment]
If you change the prefix it will indeed mess with the version as it uses the prefix to get the previous version, so if the tag changes it will not find it.

When you set `skip-commit: 'true'` it will indeed no longer update the version file as that requires the file to be committed and with the flag this is skipped.

**Comment by SHuang-Broad** [comment]
Oh, I miss understood the mechanism.
So it looks for previous release from the tag/release information, **not** from the version file.

That explains it.
