### ISSUE TITLE
skip-tag

### ISSUE THREAD

**Issue by ciesielskico** [TriPSs/conventional-changelog-action#125]
Any way to skip the git tag?
I need to do a couple of dry runs to test this action and I don't want to delete the tag anytime I run the action

**Comment by TriPSs** [comment]
Hi, no there is no option to skip the tag since the tag is used to determine the changes.

What you could try is adding the following so it will skip all git actions:
```
        env:
          ENV: 'dont-use-git'
```

**Comment by tidusjar** [comment]
@ciesielskico You can now use `git-push` and set it to `false'. This will allow you to also do a dry-run
