### ISSUE TITLE
Exception thrown, push rejected

### ISSUE THREAD

**Issue by tidusjar** [TriPSs/conventional-changelog-action#131]
Hello,

I cannot seem to get this action to work to generate the file and push the tags for the new version. 

I'm getting the following exception:

```
New version: 4.2.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v4.2.0
[releaseNotes 3790bf20] chore(release): v4.2.0
 2 files changed, 3 insertions(+), 2 deletions(-)
/usr/bin/git tag -a v4.2.0 -m v4.2.0
Push all changes
/usr/bin/git push origin releaseNotes --follow-tags
To https://github.com/ombi-bot/Ombi.git
(node:1606) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 1
 ! [rejected]          releaseNotes -> releaseNotes (fetch first)
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:574:25)
error: failed to push some refs to 'https://github.com/ombi-bot/Ombi.git'
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:557:18)
hint: Updates were rejected because the remote contains work that you do
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:1606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

You can view this yourself here: https://github.com/ombi-bot/Ombi/runs/3801765393?check_suite_focus=true

The config applied for this run is:

```
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          git-message: 'chore(release): {version}'
          version-file: 'version.json'
          output-file: 'CHANGELOG.md'
```

The `WORKFLOW_PAT` is a PAT that has full read/write to the repository and has the workflow permission.

Without providing a PAT I get the following:

```
New version: 4.1.0
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v4.1.0
[releaseNotes da366c55] chore(release): v4.1.0
 2 files changed, 7 insertions(+), 2 deletions(-)
/usr/bin/git tag -a v4.1.0 -m v4.1.0
Push all changes
/usr/bin/git push origin releaseNotes --follow-tags
To https://github.com/ombi-bot/Ombi.git
 ! [rejected]          releaseNotes -> releaseNotes (fetch first)
 ! [remote rejected]   v4.1.0 -> v4.1.0 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/ombi-bot/Ombi.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(node:1598) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:1598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TriPSs** [comment]
Could you check the rights?
` ! [remote rejected]   v4.1.0 -> v4.1.0 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)`

**Comment by TriPSs** [comment]
Check the rights of the token as GIT is saying it does not have the workflows permission. See this line:

` ! [remote rejected]   v4.1.0 -> v4.1.0 (refusing to allow a GitHub App to create or update workflow '.github/workflows/build.yml' without 'workflows' permission)`

**Comment by tidusjar** [comment]
Ok I created a new PAT with admin repo access and workflow permissions and I’m getting the same problem. 
I’d be happy to add you to the repo, it’s currently a fork of my main repo for testing purposes anyway

**Comment by TriPSs** [comment]
If i check your repo it looks like the error is always that your remote already contains changes and you therefore need to pull first. This action is not working if you run it in a matrix as then only one push is working and the others need to pull first.

I see the latest step `release` creates a tag? Maybe set the following:
```
        env:
          ENV: 'dont-use-git'
```

So that the tag and commit is not created and then run the changelog generation without it in the release step.

**Comment by tidusjar** [comment]
Ah I didn’t think about the matrix part. 

I’ll give it a go! Thanks for your assistance so far

**Comment by tidusjar** [comment]
Any idea why I’m getting the following?

https://github.com/ombi-bot/Ombi/runs/3806792278?check_suite_focus=true

**Comment by TriPSs** [comment]
Yes, this is because https://github.com/TriPSs/conventional-changelog-action/blob/master/src/helpers/git.js#L162, I forgot.

We could solve this by create a option to skip the pushing of the commit / tag, that way you can run the action multiple times in different steps.

**Comment by tidusjar** [comment]
Ah yeah. That’s pretty much what I need. I need the version to basically update my assemblies. And then later I’d successful then generate the tag and change log ☺

**Comment by TriPSs** [comment]
@tidusjar I added the `git-push` option, you can disable this to prevent it from pushing the GIT changes

**Comment by tidusjar** [comment]
Spoke too soon

‘’’

Could not find file '/home/runner/work/_actions/_temp_c8e084b1-9f40-4377-87af-af24398210e8/_staging/TriPSs-conventional-changelog-action-a0379fa/node_modules/.bin/shjs'.

‘’’

**Comment by TriPSs** [comment]
@tidusjar can you check if the latest release fixes it?

**Comment by tidusjar** [comment]
Still getting the same error
> Error: Could not find file '/home/runner/work/_actions/_temp_a491c8ca-c611-484c-b73c-515db74f48cf/_staging/TriPSs-conventional-changelog-action-2eb3616/node_modules/.bin/shjs'.

https://github.com/ombi-bot/Ombi/runs/3808257730?check_suite_focus=true

I even pinned the version to `v3.9.1` and still the same

**Comment by TriPSs** [comment]
@tidusjar see https://github.com/TriPSs/conventional-changelog-action/issues/136#issuecomment-934942130, it should be fixed now.
