### ISSUE TITLE
Is there a way to skip the Git Pull?

### ISSUE THREAD

**Issue by apr-1985** [TriPSs/conventional-changelog-action#143]
Is there a way to skip doing the Git Pull? 
I always ensure that I do a checkout [with all history and branches](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) so I do not need the extra pull. 
It is actually quite harmful where I want to be able to build my commit on a merge to `main` and then tag and release using this action. 
However if someone else merges to `main` while my commit is build then I will end up tagging and releasing the wrong commit as this extra pull will pull in the extra changes that are not part of my build.

Hope this makes sense let me know if it doesn't or if I am missing something!!

**Comment by TriPSs** [comment]
Currently this is not possible, would be a nice addition! Could you create a PR?

**Comment by apr-1985** [comment]
I will take a look tomorrow. Thought I would raise first incase I was missing something 👍
