### ISSUE TITLE
FR: add commit author to changelog

### ISSUE THREAD

**Issue by IATkachenko** [TriPSs/conventional-changelog-action#145]
# What
Now changelog line in `clean_changelog` looks like:
  `scope: title (hash)`
It would be nice if commit author will be added to title line like
  `scope: title by @user_name (hash)`

# Why
GitHub create contributors sections based on persons that was mentioned at release description. With this changes release contributors will be shown at release page.

# Alternatives
Create "contributors" output to allow users to insert this list to release notes.
But in this case contributors at release page will be doubled: one from user's release notes and second by GitHub.

**Comment by drts01** [comment]
yes please

**Comment by TriPSs** [comment]
I think this depends on the preset that is used?

**Comment by IATkachenko** [comment]
@TriPSs, hello.

Yes, in case of adding contributors to changelog.
And no, if contributors saved to variable.

Conventional changelog is allowing use [custom presets](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog) with user defined config.
Looks like `config-file-path` option may be used in GitHub action to reformat changelog lines by replacing whole config, but I was not lucky enough to do this...  It would be helpful if you could show example.
