### ISSUE TITLE
workflow question: How to release a mayor tag

### ISSUE THREAD

**Issue by diegolagospagopa** [TriPSs/conventional-changelog-action#149]
Hi,

Please can you help me to understand how to release a mayor release.

i was able to relase patchs and features tags.

But when i try:

* fix!
* patch!
* chore!
* BREAKING CHANGES

a simple patch is created

this is my repo [diegolagospagopa/demo-release-project](https://github.com/diegolagospagopa/demo-release-project/commits/main)

**Comment by TriPSs** [comment]
Syntax should be

```
feat: Your feature

BREAKING CHANGES: There is a breaking change
```

**Comment by diegolagospagopa** [comment]
Hi, 

I try as you say, but the result is the same.

You can see the action and the PR, for logs. and commits

* [action](https://github.com/diegolagospagopa/demo-release-project/runs/5002821469?check_suite_focus=true)
* [PR](https://github.com/diegolagospagopa/demo-release-project/pull/23)

**Comment by TriPSs** [comment]
You did this format:
```
BREAKING CHANGES: Your feature
```

It should be:
```
feat: Your feature

BREAKING CHANGES: There is a breaking change
```

**Comment by corquaid** [comment]
Very late follow-up question on this issue - am I correct in saying that the exclamation mark `!` syntax is not detected as a breaking change by this action, e.g. for commit types such as `feat!`?

Edit: never mind, I see that it's an issue with the Conventional Commits repo.
