### ISSUE TITLE
Feature request: Create pull request instead of directly push to the branch

### ISSUE THREAD

**Issue by skhomuti** [TriPSs/conventional-changelog-action#150]
In case of repo with protected branches I do not want to make exceptions for some automation changes on access to the protected branch. 
I guess it would be a good idea to create a pull request from a new branch with conventional changelog changes, similar to how dependabot does.
What do you think about it?

**Comment by TriPSs** [comment]
Think it's a good idea! Would you be able to create a PR?

**Comment by TheDevick** [comment]
Heey! I'm having this issue. I'm wondering if this will be implemented...

Or maybe show a way to bypass the protection?

**Comment by LironEr** [comment]
Not really a solution but... I currently remove the branch protection rules and then run the release pipeline and then turn the protection on.

Anyway there is a feature request about that [here](https://github.com/orgs/community/discussions/13836), more upvotes will probably help (:
