### ISSUE TITLE
Input to disable tag

### ISSUE THREAD

**Issue by bencat-sixense** [TriPSs/conventional-changelog-action#151]
Hello,

At first, thanks for this action, it's the best I've tried, so far :)

My question: is it possible to avoid git tag ?
Or maybe a dry run option ? 

Thanks again ;)

**Comment by TriPSs** [comment]
You can set `git-push` to false, this will prevent all changes from being pushed.

**Comment by dmijatovic** [comment]
> You can set `git-push` to false, this will prevent all changes from being pushed.

@TriPSs I tried to use `git-push: false` as a way not to push the tag when prerelease action runs. I noticed that the tag is pushed to master branch in that case. Does some other props in the configuration below interfere? I did comment out git-push option for now as it did not worked as I expected. I can solve the challenge I have using different approach.

**Comment by TriPSs** [comment]
@dmijatovic that is strange, could you share the full log? Could it be that an action that runs after the changelog one (maybe even a post task of one) causes the changes to be pushed?

**Comment by dmijatovic** [comment]
> @dmijatovic that is strange, could you share the full log? Could it be that an action that runs after the changelog one (maybe even a post task of one) causes the changes to be pushed?

@TriPSs. That's possible. I am testing number of approaches in this repo. The log is a bit long to paste it here. I made the project public now. This is the [link to action log]( https://github.com/dmijatovic/github-ci-demo/runs/5463963341?check_suite_focus=true). Let me know if you can see the log and see what could be a problem. Otherwise, when I have more time I might try to setup action in a way that causes the problem described.

**Comment by dmijatovic** [comment]
> @dmijatovic that is strange, could you share the full log? Could it be that an action that runs after the changelog one (maybe even a post task of one) causes the changes to be pushed?

@TriPSs You were right, your action will tag but not push the tag to the repo when git-push is set to false. But it can happend that some other action, that comes after, continues making changes to the repo that need to be saved and might push all changes including tags created by conventional-changelog-action.

**Comment by bencat-sixense** [comment]
@TriPSs many thanks, sorry for the delay... 
It works as expected !

I close this issue ;) Thanks again !
