### ISSUE TITLE
[Question]: Version-Bumping

### ISSUE THREAD

**Issue by XeroxDev** [TriPSs/conventional-changelog-action#158]
Hey! I'm using standard-version right now, but I would love to use your action so it's automatically after pushing to master but have one question: Does this action also support version bumping in other files then json, yml/yaml and toml? I would love to use this action for a C# project, but there's the version in an AssemblyInfo.cs.
This is how it is defined:
```cs
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
[assembly: AssemblyVersion("1.0.0")]
```
In standard-version you can define your own read/write methods for custom files and for this example it would look like this:
```js
module.exports.readVersion = function (contents) {
    var regex = /\[assembly: AssemblyVersion\(\"(.*)\"\)\]/g;
    return contents.match(regex)[0].replace(regex, "$1")
};

module.exports.writeVersion = function (contents, version) {
    var regex = /\[assembly: AssemblyVersion\(\"(.*)\"\)\]/g;
    return contents.replace(regex, `[assembly: AssemblyVersion("${version}")]`)
};
```

If you need any more information, feel free to ask!

**Comment by TriPSs** [comment]
Hi, currently this is not supported but would be an awesome addition. Could you create a PR?

**Comment by XeroxDev** [comment]
I can try my best :D

**Comment by XeroxDev** [comment]
One question... (I'm nearly done btw. Also I'll add full custom file support. This will work with a configurable regex)

Are you still developing on it yourself? Because in every issue I just read "Could you create a PR" and if this isn't done, the issue will automatically be closed with the tag: `wontfix`.

**Comment by TriPSs** [comment]
I'm still actively using it myself yes :) Just a bit to busy to add features that other people want, in the spirit of "open source" I think they can than add it them self ;)

**Comment by XeroxDev** [comment]
That's kinda right, but as example #104. This is really an important feature IMO, but it just got closed. Not everyone want or even can add those features themselves (maybe they don't know js, don't have time to look through a whole project and adapt to it and so on)
