### ISSUE TITLE
How do we pass additional params to conventional-changelog like --prerelease

### ISSUE THREAD

**Issue by michaelbarone** [TriPSs/conventional-changelog-action#159]
I have this action setup on our main branches for our core repos, bumping the version as expected.

It would be useful to bump the --prerelease version when merging into our develop branch, so we can have versioning there without affecting our production versioning.

ie:
standard bump on main branch =>  bumps Major.minor.patch normally.  < strips the -beta# value from the develop branch and bumps patch, minor, or major using standard functionality.

prerelease bump on develop branch => bumps Major.minor.patch-beta#   < only sets the beta# value on this branch.

is this possible with the current action version?  or can this be added in a future release?

**Comment by TriPSs** [comment]
Currently this is not possible.

We use `conventional-changelog` to generate the changelog, maybe they already have an option for it that we just need to pass?

**Comment by michaelbarone** [comment]
This request is for the actual version bump, not the changelog, which is part of standard-version under conventional-changelog.

conventional-changelog (standard-version) has an option for this `--prerelease`.

I was just asking if there was a way to pass this through your github action so we can easily use this flag.

https://github.com/conventional-changelog/standard-version#release-as-a-pre-release

Not sure if this is accessible with how you access conventional-changelog under the hood.
