### ISSUE TITLE
Action add [skip-ci] in commit message even if is set to false

### ISSUE THREAD

**Issue by Revocsid** [TriPSs/conventional-changelog-action#161]
Hi, 

In version v3.12.0 even if I set the input `skip-ci` to `false` or `"false"` , the action continue to add `[skip-ci]` part into the commit message.

I saw that at the line : https://github.com/TriPSs/conventional-changelog-action/blob/releases/v3/src/index.js#L46
We have 
```
const skipCi = core.getInput('skip-ci')
```
while with the other inputs of "type" boolean are processed like this 
```
const skipGitPull = core.getInput('skip-git-pull').toLowerCase() === 'true'
```

It seems like `getInput` method always return a string so this part of code is always reached (https://github.com/TriPSs/conventional-changelog-action/blob/releases/v3/src/index.js#L48)
```
if (skipCi) {
      gitCommitMessage += " [skip ci]"
    }
``` 

If you want to keep a "pure" boolean for this input, I think that you have to use the `getBooleanInput` method instead of `getInput` : https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#130

**Comment by TriPSs** [comment]
Good catch! Will check if I can fix this today.
