### ISSUE TITLE
Allow custom branch to be pushed

### ISSUE THREAD

**Issue by dhpagani** [TriPSs/conventional-changelog-action#163]
Hi guys, thank you for this awesome action!

I'm creating a 'generic' pipeline to be shared across several repositories and I'm receiving the branch name as a parameter and always getting the workflow from the default branch.

But, my problem is that the action gets the branch name from GITHUB_REF, in this part
https://github.com/TriPSs/conventional-changelog-action/blob/9b8c94a880e647cdc3e5071e15e20f0fe210b5ce/src/helpers/git.js#L5-L7
https://github.com/TriPSs/conventional-changelog-action/blob/9b8c94a880e647cdc3e5071e15e20f0fe210b5ce/src/helpers/git.js#L189
Is possible to add a parameter to receive the branch name? I can create a PR with that 

Thank you!

**Comment by TriPSs** [comment]
Yea good idea, you could create something like `CCA_REF` that would be used but if it's not defined fallback to `GITHUB_REF`
