### ISSUE TITLE
[Question] Version bumping for an older version

### ISSUE THREAD

**Issue by BeccaMG** [TriPSs/conventional-changelog-action#165]
Hello!

I have a repository with a `main` branch (which holds the V1 of the code) and a `v2` branch (which holds the V2 version of the code).

For a while, we were developing the v2 of the code and tagging it properly like v2.x.x. However, the development got interrupted and we went back to the v1 support only. Now, our changelog action tags our changes in v1 like v2.x.x (I assume it takes the latest tag and bumps it). Is there a way to ignore v2 tags for good and only bump v1 tags?

**Comment by TriPSs** [comment]
Maybe define different tag prefixes for each version?
