### ISSUE TITLE
[Question] Storing hooks and config files in external repo

### ISSUE THREAD

**Issue by soumyamahunt** [TriPSs/conventional-changelog-action#168]
I am using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) stored in a common repo for many of my actions, and would like to store the config file and hooks files in this repo. Is there any way to do this?

**Comment by TriPSs** [comment]
If I understand your correctly I don't think this is possible since the files need to be in the repo it checks out.

**Comment by soumyamahunt** [comment]
@TriPSs  Thanks for the reply, hope that GitHub provides such functionality in future. As of now, I am using a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) that wraps this action and uses [`github.action_path`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to find config files, both my composite action and reusable workflows are stored in the same repo. 

Closing this issue since the workaround is good enough for now.
