### ISSUE TITLE
[Question] Execution permission for `pre_commit_hook`

### ISSUE THREAD

**Issue by soumyamahunt** [TriPSs/conventional-changelog-action#172]
I am using this action in my swift library for automated releases as a [custom composite action](https://github.com/SwiftyLab/ci/blob/main/actions/changelog/action.yml) inside a [reusable workflow](https://github.com/SwiftyLab/ci/blob/6bdfbd50cf9b70515138aa881a611522c5dba5f2/.github/workflows/cd.yml#L47). The issue is when running [pre_commit hook](https://github.com/SwiftyLab/ci/blob/main/actions/changelog/pre_commit_hook.js) action [hangs indefinitely](https://github.com/SwiftyLab/AsyncObjects/runs/8018993851?check_suite_focus=true) with running command [`npm run generate`](https://github.com/SwiftyLab/ci/blob/main/bin/generate.js) but [runs fine when I run independently](https://github.com/SwiftyLab/AsyncObjects/runs/8030450761?check_suite_focus=true). Is there any limitation to pre_commit hook I should be aware of?

**Comment by TriPSs** [comment]
Hi, I cannot see quite clearly why this should not work, if you run the pre commit locally does it also work correctly?

**Comment by soumyamahunt** [comment]
> 



> Hi, I cannot see quite clearly why this should not work, if you run the pre commit locally does it also work correctly?

@TriPSs sorry for the late response, pre-commit-hook does run without issue both when run locally and when just running the hook in GitHub action. The issue happens when I am running the hook as part of this action itself.

**Comment by soumyamahunt** [comment]
I have moved the step containing this action to run on ubuntu runner and able to run the action successfully. This issue only happening when running with macos runner.

@TriPSs since I can use this workaround to proceed in my workflows, should I close this issue? Or do you want to track keep this open for proper closure?

**Comment by TriPSs** [comment]
@soumyamahunt lets close the issue until other ppl also have it and switching to ubuntu aint a option. Thanks for the reporting and investigating.
