### ISSUE TITLE
[Question] remove newline in end of the version file by default?

### ISSUE THREAD

**Issue by tyn1998** [TriPSs/conventional-changelog-action#175]
Hi, @TriPSs, thanks for providing such a great action!

I have a question here: if it is true that CCA will remove newline in end of the version file by default? Please see https://github.com/opensumi/devtools/pull/4#discussion_r959542074.

My workflow is: https://github.com/opensumi/devtools/blob/d2984fc78f574bef7ad06188c1ef3ff9eee49efd/.github/workflows/release.yml#L20-L26

**Comment by TriPSs** [comment]
Hmm that is a good one, I indeed think that [`JSON.stringify`](https://github.com/TriPSs/conventional-changelog-action/blob/releases%2Fv3/src/version/json.js#L48) does not add an empty line.

Maybe we can make it opt in/out.

**Comment by tyn1998** [comment]
That will be so nice!

In another [case](https://github.com/hypertrons/hypertrons-crx/blob/6c4a4930acbcf0a7c1195dc83975d25de2f2511c/scripts/bump-version.cjs#L5-L10) I use a pre-commit file to bump version manually, where the end of line is not affected because of [this](https://github.com/hypertrons/hypertrons-crx/blob/6c4a4930acbcf0a7c1195dc83975d25de2f2511c/scripts/utils.cjs#L10-L12).

**Comment by ghost** [comment]
I agree with this issue. Removing the newline is breaking my CI.

`package.json` shouldn't be modified at all outside of the version bump.

**Comment by TriPSs** [comment]
Think we can also make it auto detect by checking if the last line of the file is empty.
