### ISSUE TITLE
[Feature Request] Allow creating a change log for a specific path

### ISSUE THREAD

**Issue by AlmogBaku** [TriPSs/conventional-changelog-action#178]
By modifying this line, we can support creating a change log for a specific path (this can help to build changelogs for projects under monorepos):

https://github.com/TriPSs/conventional-changelog-action/blob/78239f16d25a195e3c21374740c952ce611c2f7a/src/helpers/generateChangelog.js#L23

**Comment by TriPSs** [comment]
Would you be wiling to create a PR?

**Comment by AlmogBaku** [comment]
@TriPSs done :P
