### ISSUE TITLE
Upgrade to Node 16

### ISSUE THREAD

**Issue by indiehjaerta** [TriPSs/conventional-changelog-action#181]
Is it possible to get an update that upgrades this to node 16

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: TriPSs/conventional-changelog-action`

**Comment by gabrielmocanu** [comment]
This would be great!
