### ISSUE TITLE
Update to new github set output commands

### ISSUE THREAD

**Issue by ray-peters** [TriPSs/conventional-changelog-action#182]
The following warnings started bubbling up inside github action workflows:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Is it possible to get an update to support the new commands and resolve the warning?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by TriPSs** [comment]
I think this is a matter of updating the `@actions/core` as we use that to set the output.

**Comment by dmijatovic** [comment]
@TriPSs I see other actions perfoming @actions/core update like [thisone](https://github.com/marvinpinto/actions/pull/546) by ([bump @actions/core from 1.4.0 to 1.10.0](https://github.com/marvinpinto/actions/pull/546/commits/4c7a8e059f62336d64cf50dd471cd6afc424529a) to resolve set-output issues in dependencies.

**Comment by ray-peters** [comment]
Thank you @TriPSs !
