### ISSUE TITLE
Failure in pre-commit hook should cause the action to report failure

### ISSUE THREAD

**Issue by randi274** [TriPSs/conventional-changelog-action#183]
This action has been great for use in our projects, but I noticed while testing out the use a script to call lerna for versioning help that when there was a failure in the pre-commit, the job was still reported as a success. Only when I drill down into the action do I see the failure. 

Here's an example action run that shows there was an error in the pre-commit, but the action still shows as successful. (The issue was that I was trying to run a separate commit in the pre-commit hook, but I'm assuming that was more of a git exception than from your action): https://github.com/randi274/salesforcedx-templates/actions/runs/3252703318/jobs/5339201187

I'd expect that when the pre-commit hook fails, the whole thing should report a failure.

**Comment by TriPSs** [comment]
Are you sure that the pre-commit file throws an error? I expect indeed that if that scripts throws a error that the action will mark it as failed.

**Comment by randi274** [comment]
Yes, I'm seeing this consistently. Here's [another](https://github.com/forcedotcom/lightning-language-server/actions/runs/3440663747/jobs/5739379625) example where we see that there was an error with the configuration on the preCommit function (WIP files), and we get the following error, but the the changelog action gives us a checkmark at the top and goes onto the next step:

```
Loading "/home/runner/work/lightning-language-server/lightning-language-server/scripts/bump-lerna-version.js" script
(node:1621) UnhandledPromiseRejectionWarning: /home/runner/work/lightning-language-server/lightning-language-server/scripts/bump-lerna-version.js:10
export function preCommit(props) {
^^^^^^

SyntaxError: Unexpected token 'export'
```
