### ISSUE TITLE
Add Dart support for version-file argument

### ISSUE THREAD

**Issue by tyler-jewell** [TriPSs/conventional-changelog-action#193]
For Dart packages, it is convenient to store the version in source code under a dart file extension. 

Can we add support for this extension? Some examples below:

file: version.dart

`
const packageVersion = '1.7.1';
`

`
const version = '1.7.1';
`

**Comment by TriPSs** [comment]
I think we can, should probably replace it like we do [here](https://github.com/TriPSs/conventional-changelog-action/blob/releases%2Fv3/src/version/toml.js#L37).
