### ISSUE TITLE
Support Cargo.lock as `version-file` for Rust projects

### ISSUE THREAD

**Issue by ChristophWurst** [TriPSs/conventional-changelog-action#194]
First of all thanks a lot for the action. It's doing an amazing job.

I wanted to add the action to a Rust project. Rust uses Cargo.toml and Cargo.lock to hold package, version and dependency info. With javascript repos I could use `version-file: package.json, package-lock.json` to keep the lock in sync with the version bump. With Rust's toml files I get

> Unhandled Rejection occurred. Error: File extension "lock" from file "Cargo.lock" is not supported

Would it make sense to add special handling that triggers toml parsing for "Cargo.lock"?

**Comment by TriPSs** [comment]
That would indeed be a good idea, we would only need to check how we could correctly do this unless `.lock` is Cargo specific?

**Comment by ChristophWurst** [comment]
PHP's composer uses composer.json and composer.lock as well. So I think the full file name should be checked because for Cargo the file is toml and for composer it's json.
