### ISSUE TITLE
Remove "Signed-off-by" footer from breaking changes in changelog

### ISSUE THREAD

**Issue by ChristophWurst** [TriPSs/conventional-changelog-action#196]
Our repos enforce a DCO with signed-off commits. I noticed that changelogs for major releases contain the full commit messages including any technical footers. This includes the "Signed-off-by Jane Doe <jane@doe.tld>" line. This clutters the generated changelog.

I would prefer if those lines were removed. Either by default or through a configuration flag.

**Comment by TriPSs** [comment]
Does this not depend on the `preset` you have configured?

**Comment by ChristophWurst** [comment]
I'm fairly new to conventional commits and releases. So far I have not touched the preset, so I must have used the angular one.
Do you have more information on how the presets influence the generation of the changelogs? I'll do my homework and read up on that.

**Comment by TriPSs** [comment]
[Here is more info](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular)

**Comment by ChristophWurst** [comment]
Thanks! I'll try to figure it out.
