### ISSUE TITLE
Want to create version (v2.0) 

### ISSUE THREAD

**Issue by IshanChakraborty96** [TriPSs/conventional-changelog-action#197]
I want to create a new version with the tag and release name (v2.0) from the package.json

**Comment by TriPSs** [comment]
Okay? Could you explain your issue?

**Comment by IshanChakraborty96** [comment]
@TriPSs Okay, When I am manually Updating the package.json fill-in to create a specific version, for example, v2.0, and merge it into the main branch I am getting the release and tag name as vnull.

But when changing the version from the package.json to v3.3.3 the release and tag name is v3.3.4 after merging into the main.

Basically, I want my release and tag name in 2 digit number for example v4.5 or v3.0.

**Comment by TriPSs** [comment]
That is something which is not possible with this lib, conventional commits uses [semver](https://semver.org/) which in their specification always has x.x.x.
