### ISSUE TITLE
Preferred way to set changelog header section

### ISSUE THREAD

**Issue by afuetterer** [TriPSs/conventional-changelog-action#201]
Hi there,

I have a short question: What would be the preferred way to set a changelog header section like:

```markdown
# Changelog

All notable changes to this project will be documented in this file. See [Conventional Commits](https://conventionalcommits.org/) for commit guidelines.
```

e.g. https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/CHANGELOG.md

Should this be defined in a [config file](https://github.com/TriPSs/conventional-changelog-action#config-file-path) or is there a better way to achieve this? Maybe generate an empty "templated" Changelog.md to which the action "appends" changes?

Any help is highly appreciated.

**Comment by TriPSs** [comment]
I can't seem to find a option to do this inside the preset/config but we can add it our selfs when we are writing the changelog the file [here](https://github.com/TriPSs/conventional-changelog-action/blob/releases/v3/src/helpers/generateChangelog.js#L76)

**Comment by afuetterer** [comment]
I see, thank you for explaining.

I found this yesterday: https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#header-string

I am a new user of the conventional-changelog-action and not quite sure how to configure it properly yet.

Feel free to close this issue, if this is out of the scope of the action.
