### ISSUE TITLE
Support for merge commits

### ISSUE THREAD

**Issue by bentonjimmy** [TriPSs/conventional-changelog-action#222]
I read over this issue: https://github.com/TriPSs/conventional-changelog-action/issues/147 but I'm looking for additional clarification on what is supported and what the assumed workflow is for this action.  I did not find any documentation on whether the angular preset supports the workflow or not.

I work with developers that do not want to squash and merge.  While testing how this action handles merge commits I also found that the commit message for the merge commit wasn't added to the change log.  It also wasn't clear to me how it would increment the version based on the commits made on the branch being merged into the main branch.  

Can someone please clarify what is assumed and supported?

**Comment by TriPSs** [comment]
As explained in #147 it all depends on the preset that is used, default is the [angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) preset, please check there. If you want different behaviour I would recommend to check what other presets there are and then using that one.
