### ISSUE TITLE
Remove duplicate entries

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [TriPSs/conventional-changelog-action#224]
Hi,

Is there a way to prevent duplicate entries in the changelog?

> program-site: use meta authentication methods for activate account btn ([469d37d](https://github.com/kingscode/emprover-ox/commit/469d37d29a7acc91e2c8aa59eb9e1f023256cd09))
> program-site: use meta authentication methods for activate account btn ([1fe3a4a](https://github.com/kingscode/emprover-ox/commit/1fe3a4a0d6059a0498851b039c7777639597024d))

The only difference is the commit, but it could be one rule with 2 references at the end. 

we try to prevent this from happening but when you create a PR of one commit it both has the same title.

**Comment by TriPSs** [comment]
This all depends on the configured preset, please also see https://github.com/TriPSs/conventional-changelog-action/issues/217, https://github.com/TriPSs/conventional-changelog-action/issues/196, https://github.com/TriPSs/conventional-changelog-action/issues/176 fore more info.

**Comment by ricardovanlaarhoven** [comment]
Thanks for the information

Is there an available preset that does this, or does this mean i would have to create my own preset?
Since it's not a simple config file but a peace of code.

**Comment by TriPSs** [comment]
I'm not quite sure sorry, there are multiple presets [inside this repo](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular), maybe one of them already does that? 

I only use the `angular` preset and never actually looked further than that 😅
