### ISSUE TITLE
Commits that do not follow conventional commits aren't included in the changelog at all

### ISSUE THREAD

**Issue by samueljoli** [TriPSs/conventional-changelog-action#228]
Enforcing conventional commits isn't perfect so for cases when commits that do not follow the conventional pattern slip through the cracks, maybe we should include an `other` section or something along those lines. An example is when a user commits from Github web, there's no way to enforce conventional commits.

If you're open to this, I can work on a pr.

**Comment by TriPSs** [comment]
Personally I believe that that should be part of the config the project uses or support for this should be added to conventional commits itself.

Question: Does git hooks not working on Github web interface?

**Comment by samueljoli** [comment]
@TriPSs Yeah Githooks only work locally. There is a server git hook called `pre-receive` but that's only for Github Enterprise 😢 . What config are you referring to?

**Comment by TriPSs** [comment]
Config of the conventional commits preset you are using.

**Comment by TriPSs** [comment]
> Optional config-file-path: Path to the conventional changelog config file. If set, the preset setting will be ignored

**Comment by samueljoli** [comment]
@TriPSs Thank you, I'll close this issue

**Comment by samueljoli** [comment]
@TriPSs Thank you, I'll close this issue
