### ISSUE TITLE
customise clean_changelog output

### ISSUE THREAD

**Issue by DerKip** [TriPSs/conventional-changelog-action#232]
The capability of configuring/defining a custom template for the clean_changelog out put would come in handy for custom changelogs.

**Comment by TriPSs** [comment]
You mean the [`config-file-path`](https://github.com/TriPSs/conventional-changelog-action?tab=readme-ov-file#config-file-path) option?

**Comment by DerKip** [comment]
I'm sorry, I overlooked this
