### ISSUE TITLE
Why are all commits now associated with user @acekevin

### ISSUE THREAD

**Issue by lukemulcahy** [TriPSs/conventional-changelog-action#236]
All the commits previously created by conventional-changelog-action user on this repo and also my repo which uses conventional-changelog-action are now attributed to @acekevin?

**Comment by TriPSs** [comment]
Hi, I just noticed this myself to.

This is a very very weird issue, i'm currenlty checking why/how this is happening.

**Comment by TriPSs** [comment]
All commits made by this action are default committed with email `conventional.changelog.action@github.com`, somehow Github is that now linking to @acekevin.

**Comment by TriPSs** [comment]
FYI: I created a ticket with @github for this.

**Comment by lukemulcahy** [comment]
Thanks! 

Is there any vulnerability risk around this regarding private repos? Say I have been use the conventional.changelog.action@github.com to commit to my private repo? I've since changed the email to my own.

**Comment by TriPSs** [comment]
I do not see any reason for a risk here, having commits assigned to someone in a repo does not give one access to do anything in it nor see it.

I think Github mis-assigned this email address to a user causing their system to think these commits are made by him.

**Comment by lime517** [comment]
Just noticed this as well. Thank you for being on top of figuring it out!

**Comment by TriPSs** [comment]
Github solved the issue, they removed the email address from the users account and have prevented it from being added to any other account. They also confirmed that this is/was not a security issue, [as is mentioned in their documentation](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user).

**Comment by lukemulcahy** [comment]
Great stuff! Thank you
