### ISSUE TITLE
Access previous issue as an output

### ISSUE THREAD

**Issue by BrianKopp** [TriPSs/conventional-changelog-action#240]
Hi there! This is a great project, thanks for having it!

I am looking to further automate my release process by automatically updating my documentation to point from the previous version to the current version.

Is there an existing way to get the previous version as an output from the action?

If not, I would be happy to contribute that, if you'd be open to that!

Thanks again!

**Comment by TriPSs** [comment]
Currently it is not outputted, you can add it here if you want:

https://github.com/TriPSs/conventional-changelog-action/blob/releases/v4/src/index.js#L225-L229
