### ISSUE TITLE
Breaking changes not recognized when using `!`

### ISSUE THREAD

**Issue by MuchaSsak** [TriPSs/conventional-changelog-action#241]
### Conventional Commit guidelines show that breaking changes can be labeled using the exclamation mark.
<img width="600" src="https://github.com/TriPSs/conventional-changelog-action/assets/107958275/ecfdc45b-c7e3-4eda-9821-d1b065ec6818" alt="Conventional Commits screenshot" />

### However, this does not work for me:
`git commit -m "feat!: this is breaking, but is not recognized"`

**Comment by TriPSs** [comment]
That is because default the `angular` preset is used, where using the `!` is [optional](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#commit-message-with-optional--to-draw-attention-to-breaking-change).

Please also search existing issues (#217)
