### ISSUE TITLE
Is it possible to export `contributors` list tot `output`?

### ISSUE THREAD

**Issue by greenhat616** [TriPSs/conventional-changelog-action#250]
As this quote https://github.com/TriPSs/conventional-changelog-action/issues/145#issuecomment-1066121959 referred. 

It could be better to export a contributors list to help us to generate the contributors section like below:

![image](https://github.com/TriPSs/conventional-changelog-action/assets/41122242/ea8df3db-a084-4f2b-9a3f-ff9dfd6f45ee)

**Comment by TriPSs** [comment]
Like said in that ticket, added this to your changelog would depend on the preset. If you still want this and the preset does not default support it you can use the [config-file-path](https://github.com/TriPSs/conventional-changelog-action?tab=readme-ov-file#config-file-path)
