### ISSUE TITLE
Dry run not working

### ISSUE THREAD

**Issue by mr-j0nes** [TriPSs/conventional-changelog-action#252]
I am using version 4.

I would like to run conventional-changelog-action (as a dry run)  first to get the next version in order to build my installation files. Once I know nothing fails I would like to run conventional-changelog-action in commit mode to really reflect the changes into version.json, and create the tag.

With "dry run" I mean to run conventional-changelog-action to get the next version but not writing anything. For this I use following modifiers:

```
          git-push: false
          skip-commit: true
          skip-tag: true
```
But this does not seem to work as the version retrieved is always the fallback one:

```
Using GIT to determine the new version
The version could not be detected, using fallback version '0.1.0'.
Changelog generated
# 0.1.0 (2024-02-16)
```
The normal run reads from version.json getting the real version (0.6.0).

How can I achieve a dry run?

**Comment by TriPSs** [comment]
Could you share your full workflow + log?

Only setting `git-push` to `false` should be sufficient, `skip-commit` and `skip-tag` can't be used together as it can't determine any version at that point so it will fallback to the fallback version.

After everything is than ok you won't need to run the action again but could just `git push` if i'm not mistaken.

**Comment by mr-j0nes** [comment]
Thank you for the quick reply. I was running `conventional-changelog-action`  two times. But running `git push` at the end makes more sense. I'll try that. Thanks.
