### ISSUE TITLE
how to use input-file?

### ISSUE THREAD

**Issue by ghost** [TriPSs/conventional-changelog-action#256]
how to use input-file?
name: icms-web
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 获取pnpm store目录
        id: pnpm_cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 设置pnpm缓存
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm_cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        if: steps.pnpm_cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: 打包构建
        run: pnpm run build

      - name: 变更日志
        id: change_log
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pre-release: false
          skip-git-pull: true
          input-file: "./MOTIFY.md"

      - name: 压缩
        run: tar -zcvf icms-web-${{steps.change_log.outputs.version}}.tgz icms-web-${{steps.change_log.outputs.version}}

      - name: 发布版本
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{steps.change_log.outputs.version}}
          files: icms-web-${{steps.change_log.outputs.version}}.tgz
          prerelease: false
          draft: false
          name: v${{steps.change_log.outputs.version}}
          body: ${{steps.change_log.outputs.clean_changelog}}

....

---
<img width="264" alt="Snipaste_2024-03-11_17-10-49" src="https://github.com/TriPSs/conventional-changelog-action/assets/123848943/4318400c-3d73-4a1b-9a14-51c49ebc1c57">

**Comment by TriPSs** [comment]
As you are doing here, what is the issue?

**Comment by ghost** [comment]
changelog empty 
![IMG_0188](https://github.com/TriPSs/conventional-changelog-action/assets/123848943/7e3752f2-7f8e-4895-8cea-b1113f079b98)

**Comment by TriPSs** [comment]
Okay? It says it right there in the logs, the generated changelog is empty and `skip-on-empty` is not set to `false`.

**Comment by ghost** [comment]
But there is content in this file（MOTIFY.md）

**Comment by TriPSs** [comment]
Yes, but the **generated changelog** is empty, if you want empty generated changelogs that set `skip-on-empty` to `false`
