### ISSUE TITLE
 version-file does not accept yarn.lock file

### ISSUE THREAD

**Issue by tiavina-mika** [TriPSs/conventional-changelog-action#263]
Hello.
 
 I'm using `yarn `instead of `npm`, so the lockfile is `yarn.lock` instead of `package-lock.json`.
 
 Since verion-file accept only  .yml, .yaml, .toml, mix.exs, .json.
 
 What should I do?

**Comment by TriPSs** [comment]
Don't think the `yarn.lock` file keeps a version that is also in the `package.json`, so don't think this is needed.
