### ISSUE TITLE
Major version is not bumped on pre-release

### ISSUE THREAD

**Issue by bj00rn** [TriPSs/conventional-changelog-action#272]
Seems that pre release is not bumping major version correctly. Is this intended behaviour.

I would expect that a pre-release with a breaking change would bump version number. In this case release should be `v6.0.0-rc.0` even though previous release was v5.1.1-rc.0.

Or is this intended behaviour?

extract from logs at https://github.com/bj00rn/ha-saleryd-ftx/actions/runs/12018170980/job/33502074725
```

Already up to date.
Recommended release type: major
Because: There is 1 BREAKING CHANGE and 0 features
Files to bump: custom_components/saleryd_hrv/manifest.json
Bumping version to file "custom_components/saleryd_hrv/manifest.json" with extension "json"
Bumped file "/home/runner/work/ha-saleryd-ftx/ha-saleryd-ftx/custom_components/saleryd_hrv/manifest.json" from "5.1.1-rc.0" to "5.1.1-rc.1"
Changelog generated
## [5.1.1-rc.1](https://github.com/bj00rn/ha-saleryd-ftx/compare/v5.1.1-rc.0...v5.1.1-rc.1) (2024-11-25)


### ⚠ BREAKING CHANGES

* Remove mode switches replaced by select. Remove state attributes

### Features

* major refactor ([a4f6662](https://github.com/bj00rn/ha-saleryd-ftx/commit/a4f6662c4a5de387f2f9ab3672b7f0dea20ef86e))


New version: 5.1.1-rc.1
/usr/bin/git add .
/usr/bin/git commit -m chore(release): v5.1.1-rc.1
[master 5154e96] chore(release): v5.1.1-rc.1
 2 files changed, 12 insertions(+), 9 deletions(-)
/usr/bin/git tag -a v5.1.1-rc.1 -m v5.1.1-rc.1
Push all changes
/usr/bin/git push origin master --follow-tags
To https://github.com/bj00rn/ha-saleryd-ftx.git
   e4bfff2..5[154](https://github.com/bj00rn/ha-saleryd-ftx/actions/runs/12018170980/job/33502074725#step:3:155)e96  master -> master
 * [new tag]         v5.1.1-rc.1 -> v5.1.1-rc.1
 
```

**Comment by TriPSs** [comment]
Not 100% sure but I think the pre release always does `-rc.x` where x is one more then the previous. The `semver` package is used to do the actual bumping, you can check [there](https://github.com/npm/node-semver) for more info.

**Comment by bj00rn** [comment]
> Not 100% sure but I think the pre release always does `-rc.x` where x is one more then the previous. The `semver` package is used to do the actual bumping, you can check [there](https://github.com/npm/node-semver) for more info.

Thanks, had a Quick Look at the docs and it seems you are correct. `prerelease` arg will bump only pre release version. I’m guessing `pre[major|minor|patch]` respectively need to be passed to semver to achieve what im after.

I think that would be a really nice feature if the action would take version bump type into consideration when bumping pre release




```
-i --increment [<level>]
        Increment a version by the specified level.  Level can
        be one of: major, minor, patch, premajor, preminor,
        prepatch, or prerelease.  Default level is 'patch'.
        Only one version may be specified.
```

**Comment by TriPSs** [comment]
Now that i'm looking further in the code, I think we implemented `prerelease` incorrectly:
```
    newVersion = semver.inc(version, (prerelease ? 'prerelease' : releaseType), identifier)
```

We should send the `prerelease` value based off what `releaseType` is, so if `releaseType` is `major` (like in the logs you linked) we then need to send `premajor` indeed to semver.

Is this something you could create a PR + test for?

**Comment by bj00rn** [comment]
I don't think I have the bandwidth right now to get started on `act` etc i'm afraid.

Im guessing something in the ways of below, would suffice.

```javascript
 newVersion = semver.inc(version, (prerelease ? `pre${releaseType}` : releaseType), identifier)
```

**Comment by bj00rn** [comment]
@TriPSs gave it a shot in #273. Probably should have some more tests with premajor, prepatch and subsequent stable release.

**Comment by TriPSs** [comment]
@bj00rn thanks for the PR, it's released as `v6`
