### ISSUE TITLE
pre-release

### ISSUE THREAD

**Issue by jcornaz** [TriPSs/conventional-changelog-action#38]
Hi, 

Is it possible to have pre-release channels with this utility?

Let's say that I want to publish stable releases for each commit on by `main` branch, while publishing `beta` releases for each commit in a `beta` branch.

Is that possible?

**Comment by TriPSs** [comment]
It should be possible to generate a changelog on for example the `beta` branch with different tags (separate workflow with different config) but i'm not sure if you then merge that branch into the `main` branch if it will generate a full changelog based on other tags. 

If convential commits cli works with tag postfixes and filters those out then we can also make it work with this action.

**Comment by TriPSs** [comment]
I checked they don't support post fixes, this is still possible:
1. Create separate workflows for the `beta` and `main` branches
1. `beta` branch get's workflow with `tag-prefix` being something like `beta-`, this will create tags like `beta-1.2.3`
1. `main` branch get's workflow with default prefix

I'm not 100% sure but I think this should work, you can even let the `beta` branch write the changelog to a different file.

**Comment by jcornaz** [comment]
> beta branch get's workflow with tag-prefix being something like beta-, this will create tags like beta-1.2.3

No, that doesn't work. `beta-1.2.3` a not a semantic version, but a *tag* to a version *beta* version `1.2.3` but `1.2.3` is not a pre-release semantic version.

For instance a breaking change on the branch `beta` would bump from `beta-1.2.3` to `beta-2.0.0`. But it should bump from `1.2.3-beta.1` to `1.2.3-beta.2`.

**Comment by TriPSs** [comment]
I get where you are going but I don't see that working atm, the steps I described was to at least get kind of correct  changelogs out of it.

**Comment by jcornaz** [comment]
> I checked they don't support post fixes,

@TriPSs May I ask who is "they"?

**Comment by TriPSs** [comment]
@jcornaz [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog), this action uses packages from them.

**Comment by jcornaz** [comment]
But [conventional-changelog/standard-version](https://github.com/conventional-changelog/standard-version) (as recomanded in the "Getting started" of the page you linked, does support prerelease:

https://github.com/conventional-changelog/standard-version

Can you give more detail on the technical limitation your facing?

**Comment by TriPSs** [comment]
@jcornaz We don't use the `standard-version` we use [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-recommended-bump/README.md), the pre-release is custom logic in the standard version and is not provided in bumper. You are welcome to make a PR that will also implement this logic.

**Comment by jcornaz** [comment]
Ok, I see. Thanks for the info.

**Comment by bcullman** [comment]
@TriPSs - 

`conventional-recommended-bump` recently added skipunstable in ` 6.1.0`

https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#skipunstable

ANy chance this would mean they now support pre-releases as described above out-of-the-box?
