### ISSUE TITLE
`package-lock.json` won't update

### ISSUE THREAD

**Issue by andresmatasuarez** [TriPSs/conventional-changelog-action#43]
Deliberate duplicate of https://github.com/TriPSs/conventional-changelog-action/issues/8 (closed automatically)

I'm about to rewrite my whole action without changelog because of this. Is there a reason why `package-lock.json` is not being taken into consideration when bumping version?

I'll gladly work on a patch and submit a PR if I'm given the green light.

**Comment by TriPSs** [comment]
Hi @andresmatasuarez, as far as i'm aware the `conventional-changelog` cli also does not do this. Could you clarify why this is needed?

Also you are welcome to create a PR that checks if there is a `package-lock.json` file, or maybe update the `version-file` to accept comma separated paths so you can add your `package.json` and your `package-lock.json`

**Comment by andresmatasuarez** [comment]
Hi @TriPSs, not bumping version in both `package.json` and `package-lock.json` inevitably results in a discrepancy between the two which causes tools like `npm ci` not to work, which my team rely heavily on in our project, as do a lot of other teams as well, I'd say.

I like the comma-separated proposal so I'd go with it. I'll have it ready for review no later than tomorrow :)

**Comment by TriPSs** [comment]
This is released in [v3.2.0](https://github.com/TriPSs/conventional-changelog-action/releases/tag/v3.2.0) :tada:
