### ISSUE TITLE
`skip-on-empty` is true by default

### ISSUE THREAD

**Issue by andresmatasuarez** [TriPSs/conventional-changelog-action#47]
hey @TriPSs, due to the recent PR I did, I noticed I was using v2 instead of v3 so I decided to make the switch. Sadly, my workflow started to fail somehow and I found out that `skip-on-empty` isn't defaulting to `false` as per the docs. It all started to come back together again once I explicitly declared `skip-on-empty: false` on my workflow yaml.

It'd be great if you could take a real quick look at this and let me know if you wish me to patch it, I don't mind doing it, seems a microscopic fix

**Comment by TriPSs** [comment]
Hi @andresmatasuarez, could you check what your logs said when it failed? And then specifically this part:
`Skipping empty releases is`

**Comment by andresmatasuarez** [comment]
Failing workflow said `Skipping empty releases is enabled` while the previous one before the update (working) said nothing (since apparently `skip-on-empty` was non-existent on v2). As I said, I had to manually set `skip-on-empty: false` on my workflow yaml file to get back to normal.

also, I a quick glance over the code revealed that `skip-on-empty` might actually be defaulting to `true`:
https://github.com/TriPSs/conventional-changelog-action/blob/ca16f2de01f41abb0fc435ddadd274c144ffec89/action.yml#L69

**Comment by TriPSs** [comment]
I see, looked at the history and see that the default value changed with the release and that the README is not updated.

When this feature was added it was added with default false since it was a behaviour change, I'm in favour of keeping the default on `true` and updating the README.

**Comment by andresmatasuarez** [comment]
cool, I'll do a quick patch sometime during the day then

**Comment by TriPSs** [comment]
Thanks, much appreciated!

**Comment by TriPSs** [comment]
This is released in [v3.3.0](https://github.com/TriPSs/conventional-changelog-action/releases/tag/v3.3.0)

**Comment by TriPSs** [comment]
Thank you @andresmatasuarez for the contribution!
