### ISSUE TITLE
Not able to save version in my package.json while updating our TriPss version from 1.3.0 to latest version

### ISSUE THREAD

**Issue by adityaSharma369** [TriPSs/conventional-changelog-action#57]
previously i'm using TriPSs v1.3.0 in my github actions iam able to bump my version and storing it in my package.json but when i tried to use latest version my package.json is not updating with my bumped version.
![version bump](https://user-images.githubusercontent.com/53860201/90760619-c782d700-e2ff-11ea-9a5a-57b66e584f1c.png)

**Comment by TriPSs** [comment]
Hi, could you provide me some logs?

Could you also share how you configured version v3?

**Comment by adityaSharma369** [comment]
hey hi..sorry for late response..
actually i used same configuration for version 3 i just replaced version V1.3.0 to V3 
and also tried below configuration
![p1](https://user-images.githubusercontent.com/53860201/91279792-942ec500-e7a3-11ea-86d4-5492ad92a43c.png)
 and this is my logs
![p2](https://user-images.githubusercontent.com/53860201/91280164-056e7800-e7a4-11ea-8bc6-6898e21b12d6.png)
the version is updating but the updated value is not stored in package.json

**Comment by TriPSs** [comment]
The last line of the logs tells that the changelog generated was empty, in V3 empty changelogs no longer bump / tag / push the version that is because the default behavior of this option is changed
> Optional skip-on-empty: Boolean to specify if you want to skip empty release (no-changelog generated). This case occured when you push chore commit with angular for example. Default 'true'.

If you want this behavior back you enable it with `skip-on-empty: "true"`

**Comment by adityaSharma369** [comment]
thanks for the info ...will do that
