### ISSUE TITLE
Generate Changelog ONLY - no tags, no commits

### ISSUE THREAD

**Issue by gpiffaretti** [TriPSs/conventional-changelog-action#58]
Hey guys, I'm loving this action, keep the good work! Hopefully I'm able to collaborate at some point :)

I was wondering if there's a way to generate a changelog only, that doesn't generate any commits or tags.
In our process we might need a way to generate a changelogs that includes changes from version X to version Y, including all the commits in that range. Would that be possible with the current implementation?

**Comment by TriPSs** [comment]
Hi, this would be kinda hard as the action needs a value to determine it's current and next version on. Also if no tag is created it would be unable to determine the new changes.

So short answer: No, this is currently not possible.

**Comment by TriPSs** [comment]
Ofc are ideas on how to improve this action always welcome :)

**Comment by gpiffaretti** [comment]
Yeah makes sense, thanks for the quick response.
