### ISSUE TITLE
version-file extension not supported even if it's YML inside

### ISSUE THREAD

**Issue by gpiffaretti** [TriPSs/conventional-changelog-action#59]
I'm using this action in a Unity project.
Unity keeps the version number in a file named "ProjectSettings.asset". It's just an YML with a custom extension.
And as you can see I'm getting the following error when it tries to use that file.

```(node:3015) UnhandledPromiseRejectionWarning: Error: File extension "asset" from file "./GBAR/ProjectSettings/ProjectSettings.asset" is not supported
    at handleVersioningByExtension (/home/runner/work/_actions/TriPSs/conventional-changelog-action/v3/src/index.js:15:11)```

Maybe it would be useful to specify an optional input `version-file-type` so that it uses that format instead of inferring it from extension? And if no type is specified, just work as it's been working.

**Comment by TriPSs** [comment]
Hi @gpiffaretti, that would be a great addition! When a `version-file-type` is defined we can use that one and if not determine it ourselfs.

Would you like to create a PR?

**Comment by gpiffaretti** [comment]
Created this pull request :)
https://github.com/TriPSs/conventional-changelog-action/pull/61

**Comment by gpiffaretti** [comment]
Tried it in my own fork and it's working. I had to do another addition to make it work with Unity:

`fileContent.replace(
          `${versionName}: '${oldVersion}'`,
          `${versionName}: '${this.newVersion}'`,
        )`

That part won't work because Unity doesn't use the `'` character for the values in the YML file.
I had to change the replace logic but haven't added an option to choose if using the `'` or not. I also don't wanna add too much complexity with too many parameters and stuff. What do you think?

**Comment by TriPSs** [comment]
Maybe a simple check like `const quoteType = fileContent.includes(`'${oldVersion}'`) ? `'` : `"``?
