### ISSUE TITLE
Git push with LFS

### ISSUE THREAD

**Issue by gpiffaretti** [TriPSs/conventional-changelog-action#62]
My version-file is tracked by LFS. I know it's weird but my version file is a .asset file in Unity and there are some other big .asset files so I need to do this.

After the action, the reference is pushed correctly, but when I want to checkout the new commit I get an error because the object does not exist:

```
Downloading Project/ProjectSettings/ProjectSettings.asset (21 KB)
Error downloading object: Project/ProjectSettings/ProjectSettings.asset (2a0c91c): Smudge error: Error downloading Project/ProjectSettings/ProjectSettings.asset (2a0c91c166259d18151ed53c89e8ad8676c428dae2a6ea70c0dfb8a498ca3272): [2a0c91c166259d18151ed53c89e8ad8676c428dae2a6ea70c0dfb8a498ca3272] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to /home/user/Projects/Project/.git/lfs/logs/20200829T000520.913474364.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Project/ProjectSettings/ProjectSettings.asset: smudge filter lfs failed
```

I tried adding a `git lfs push origin ${branch}` after the normal push in this action but it didn't work. Need to dive deeper into this.

**Comment by TriPSs** [comment]
Hi,

I have no experience with LFS, is it maybe possible to make a example repo?

**Comment by gpiffaretti** [comment]
Yeah of course, will create one when I get some time.
