### ISSUE TITLE
Question: Jira Compatability

### ISSUE THREAD

**Issue by Kimba666** [TriPSs/conventional-changelog-action#63]
What Jira functionalities does this action support? 

What I'm trying to do is have the commit message contain the Jira Issue Key for the related jira task, as a clickable link that will take the user to the corresponding Jira task. 

An example commit would be something like~ "git commit -m 'fix: addressed a bug on the dashboard [JIRA-123]'

And then in the actual Commit Message within the Changelog.md created from the action, the "[JIRA-123]" would be a hyperlink to the jira task that is related to that changelog entry. 

Is this possible with this action?

**Comment by TriPSs** [comment]
Hi @Kimba666,

Yes i think this is possible with the `config-file-path` option, how to configure it properly would then be a question for the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) guys.

**Comment by Kimba666** [comment]
Understood, thank you. I'll continue to tinker around. :)
