### ISSUE TITLE
Not bumping the package.json or creating the tag

### ISSUE THREAD

**Issue by Tbaut** [TriPSs/conventional-changelog-action#64]
Hi and thank you very much for the action.
When I run the action with mostly default actions, things are not working as expected, although the logs don't show any error.

The changelog is not updated and the `package.json` not bumped.
Here is my action file https://github.com/paritytech/substrate-js-utils/blob/master/.github/workflows/bump_version.yml#L36

And the logs show:

```bash
Using "conventional.changelog.action@github.com" as git user.email
Using "5" release count
Using "./react-context/package.json" as version file
Using "version" as version path
Using "" as tag prefix
Using "./react-context/CHANGELOG.md" as output file
Using "" as config file
Skipping empty releases is "enabled"
Skipping the update of the version file is "disabled"
Pull to make sure we have the full git history
/usr/bin/git config user.name Conventional Changelog Action
/usr/bin/git config user.email conventional.changelog.action@github.com
/usr/bin/git remote set-url origin ***github.com/paritytech/substrate-js-utils.git
/usr/bin/git pull --unshallow --tags --ff-only
From https://github.com/paritytech/substrate-js-utils
 * [new tag]         0.6.0      -> 0.6.0
Already up to date.
Recommended release type: patch
Because: There are 0 BREAKING CHANGES and 0 features
Files to bump: ./react-context/package.json
Bumping version to file "./react-context/package.json" with extension "json"
Changelog generated
## [0.6.1](https://github.com/paritytech/substrate-js-utils/compare/0.6.0...0.6.1) (2020-09-15)




Generated changelog is empty and skip-on-empty has been activated so we skip this step
```

**Comment by TriPSs** [comment]
Hi @Tbaut, the last line says it ;)
`Generated changelog is empty and skip-on-empty has been activated so we skip this step`

If you want to generate empty changelogs pls add the following to the action:
```
with:
   skip-on-empty: 'false'
```

**Comment by Tbaut** [comment]
Thanks for the super quick reply. I'm wondering why it's empty though. There is a commit, it's following the convention afaik (it's here https://github.com/paritytech/substrate-js-utils/commit/599238510fddae5beab03b6ce16ec0f9e1213896)

**Comment by TriPSs** [comment]
That is because bumps normally only happen when you commit with `feat`, `fix` or if the commit body contains `BREAKING CHANGES` for a major version bump.

**Comment by Tbaut** [comment]
Understood, thanks a lot for the explanations.
