### ISSUE TITLE
skipTag no longer works

### ISSUE THREAD

**Issue by bsord** [TriPSs/conventional-changelog-action#67]
Can you re-add skipTag?
Seems it was removed here as part of a refactor. 
https://github.com/TriPSs/conventional-changelog-action/commit/f4bda96138755bbed2ff560659f6e98ae48295f7#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L104-L107

**Comment by TriPSs** [comment]
Hi, this is removed because `conventional-recommended-bump` needs tags to determine the new changes and recommend us with the bump type.

**Comment by TriPSs** [comment]
I think you can achieve this by adding:
```
  env:
    ENV: 'dont-use-git'
```

This will prevent everything from being pushed and then you can use the output from this step, if needed you can also `git reset --hard head` to undo all the file changes etc.

May I ask why you need to need to skip everything in step 2 but need it again in step 4?

**Comment by TriPSs** [comment]
Closing this as it's currently not the plan to re add this.

**Comment by bsord** [comment]
Thanks, the dont-use-git option works for me. I use the version and tag information to write some additional changes to the repo using the version/tag output. I want these changes made prior to the actual version release by this action, hence the dry run ask.

**Comment by bsord** [comment]
Actually dont-use-git doesn't work because i'm relying on git for the version bump (skipping version file) because i'm trying to make this workflow as universally compatible across all my repos as possible. When i skip version file, but also specify dont-use-git, it fails to get the tag/version number and just assumes 0.1.0 and always starts at the bottom

**Comment by TriPSs** [comment]
Maybe you can use the 'pre-commit' functionality to achieve what you want?
