### ISSUE TITLE
Yaml does not support double quotes or no quotes

### ISSUE THREAD

**Issue by nstrelow** [TriPSs/conventional-changelog-action#71]
I have a flutter project with a so called pubspec.yaml, which by default specifies the version without quotes.

In the code the yaml.js file the replace function expects single quotes. Yaml usually doesn't care if it is single, double or no quotes.

**Comment by TriPSs** [comment]
Hi @nstrelow, this was partly discussed in #59, a PR to solve this is very welcome :).

The reason that is always a quote and not without quotes is to force it to be an string, do you have an issues with using the quoted version number?

**Comment by nstrelow** [comment]
I do not have an issue, but it took me a long time to figure out.

The default for flutter projects is without quotes. I created this issue, so that others would not have to search around like me :)

I will see if I can produce a fix sometime.

**Comment by miroslav-staffa** [comment]
Thank you for opening this issue, I fell into the no quotes trap myself it helped me a lot. I agree that it would help to document this somehow. But maybe this was caused by me not having too great knowledge about YAML.

**Comment by TriPSs** [comment]
This feature had been added in [v3.7.0](https://github.com/TriPSs/conventional-changelog-action/releases/tag/v3.7.0)
