### ISSUE TITLE
arbitrary file extension

### ISSUE THREAD

**Issue by bmahlbrand** [TriPSs/conventional-changelog-action#73]
We have a usecase where we have valid json file that happen to be named something else (like.uplugin or .uproject). Is it possible to set a flag to tell it to just accept this extension as json?

**Comment by bmahlbrand** [comment]
It's possible to workaround this with using the output flags from the action, but I'm still curious if it makes sense to be a feature or not.

**Comment by TriPSs** [comment]
Hi, this is currently not possible. An PR is always welcome, #61 was created by someone els and was almost done.
