### ISSUE TITLE
Provide custom tag instead of bumping automatically from file

### ISSUE THREAD

**Issue by kurnev** [TriPSs/conventional-changelog-action#76]
Hello,

We are quite happy with your action, but would like to provide custom tags lower than current version to the action inputs. In our case we have two different versions for staging and prod and this is what we use to deploy hotfix on prod. Are you open for PR for this feature?

**Comment by TriPSs** [comment]
Hi, yes that would be awesome!

If I understand correctly you want to ability to modify the new version? If so maybe it's an idea to do it similar to `pre-commit` , that users can provide a `pre-changelog-generation` where they get the same info as `pre-commit` but where they are able to modify and return `tag` and `version` which will then be used for the changelog and tag.

**Comment by kurnev** [comment]
Yeah, we want the ability to provide our custom tag instead of what preset has generated and use it later on as a tag and in changelog.

Sound reasonable with `pre-changelog-generation`. Thanks for quick reply

**Comment by TriPSs** [comment]
Thanks for the PR! This has been released in [v3.5.0](https://github.com/TriPSs/conventional-changelog-action/releases/tag/v3.5.0) and v3 has been updated
