### ISSUE TITLE
Doesn't update package-lock.json

### ISSUE THREAD

**Issue by craigsketchley** [TriPSs/conventional-changelog-action#8]
Cheers for the action. Couple of things I noticed... this currently leaves `package-lock.json` untouched - shouldn't it update the version in that too? Also, it removes the newline at the end of the file when writing back to `package.json`.

**Comment by andresmatasuarez** [comment]
+1 for this, I'm about to rewrite my whole action on account of this, any reason `package-lock` is not updated? I'll gladly work on a patch myself
