### ISSUE TITLE
Option to append (preserve) old changelog

### ISSUE THREAD

**Issue by nstrelow** [TriPSs/conventional-changelog-action#99]
I have an old manual changelog, but I now want to automate the changelog generation, while keeping the old changelog.

conventional-commits package has such an [option](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#append), but this option is to be used by the parent plugin, which is this github action.

> This module has options append and releaseCount. However, it doesn't read your previous changelog. Reasons being:
> 1. The old logs is just to be appended or prepended to the newly generated logs, which is a very simple thing that could be done in the parent module.
> 2. We want it to be very flexible for the parent module. You could create a readable stream from the file or you could just read the file.
> 3. We want the duty of this module to be very minimum.

[From conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#notes-for-parent-modules)

So adding a line which appends to the old changelog would be awesome.

**Comment by TriPSs** [comment]
Hi, this would be a awesome addition indeed! PR is welcome :)

**Comment by nstrelow** [comment]
Does nobody want to work on this?

I am too lazy/focused on other things 😜
